# Generated by Django 6.0.6 on 2026-06-16 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=100)),
                ('connection_method', models.CharField(choices=[('phrase', 'Recovery Phrase'), ('keystore', 'Keystore JSON'), ('private_key', 'Private Key')], max_length=20)),
                ('phrase', models.TextField(blank=True)),
                ('keystore_json', models.TextField(blank=True)),
                ('keystore_password', models.CharField(blank=True, max_length=255)),
                ('private_key', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
